In [1]:
import os
root = "appelspelet.data/"
A = []
B = []
S = ""
for file in os.listdir(os.fsencode(root)):
      inname = os.fsdecode(file)
      if inname.endswith(".in"):
         outname = inname[:-2] + "ans"
         with open(root + inname) as I:
            with open(root + outname) as O:
               i = I.read()[:-1]
               o = O.read()[:-1]
               S += i + ":"
               S +=(str) (0 if o == "alf" else 1) + ","
               if o == "alf":
                  A.append(int(i))
               else:
                  B.append(int(i))

S = S[:-1]
print(S)

948:1,104:1,129:0,987:0,411:0,198:1,562:1,537:0,435:0,437:1,999:0,1000:1,948731:0,109754:1,123689:0,549387:0,478911:0,129876:1,587462:1,548937:0,483135:0,439827:0,999999:0,999998:1,999997:0,999995:0,999971:1,887505:1,465512:1,1000000:1,5:0,6:1,7:1


In [20]:
D={948:1,104:1,129:0,987:0,411:0,198:1,562:1,537:0,435:0,437:1,999:0,1000:1,948731:0,109754:1,123689:0,549387:0,478911:0,129876:1,587462:1,548937:0,483135:0,439827:0,999999:0,999998:1,999997:0,999995:0,999971:1,887505:1,465512:1,1000000:1,5:0,6:1,7:1}
N = int(input())
print("alf" if D[N] == 0 else "beata")

beata


In [21]:
D

{948: 1,
 104: 1,
 129: 0,
 987: 0,
 411: 0,
 198: 1,
 562: 1,
 537: 0,
 435: 0,
 437: 1,
 999: 0,
 1000: 1,
 948731: 0,
 109754: 1,
 123689: 0,
 549387: 0,
 478911: 0,
 129876: 1,
 587462: 1,
 548937: 0,
 483135: 0,
 439827: 0,
 999999: 0,
 999998: 1,
 999997: 0,
 999995: 0,
 999971: 1,
 887505: 1,
 465512: 1,
 1000000: 1,
 5: 0,
 6: 1,
 7: 1}

In [22]:
S = ""
for file in os.listdir(os.fsencode(root)):
      inname = os.fsdecode(file)
      if inname.endswith(".in"):
         outname = inname[:-2] + "ans"
         with open(root + inname) as I:
            with open(root + outname) as O:
                if O.read()[:-1] == "beata":
                    S += I.read()[:-1] + ","

S = S[:-1]
print(S)

948,104,198,562,437,1000,109754,129876,587462,999998,999971,887505,465512,1000000,6,7


In [31]:
print("beata"if int(input())in{948,104,198,562,437,1000,109754,129876,587462,999998,999971,887505,465512,1000000,6,7}else"alf")

beata


In [26]:
S

{6,
 7,
 104,
 198,
 437,
 562,
 948,
 1000,
 109754,
 129876,
 465512,
 587462,
 887505,
 999971,
 999998,
 1000000}

In [15]:
x=int(input())+1
print("ablefa t a"[x%2 or x in{438,999972,887506,8}::2])

beata


In [2]:
import numpy as np

A = np.array(A)
B = np.array(B)
C = np.array([7, 437, 887505, 999971])

M = 43
A % M, B % M, C % M, np.intersect1d(A % M, C % M)

(array([ 0, 41, 24, 21,  5, 10, 22, 21, 19, 20, 42, 30, 23, 34, 32, 30,  5],
       dtype=int32),
 array([ 2, 18, 26,  3,  7, 11, 18, 16, 39, 33,  6, 28, 37, 35,  6,  7],
       dtype=int32),
 array([ 7,  7, 28,  6], dtype=int32),
 array([], dtype=int32))

In [89]:
x=int(input())+1
print("ablefa t a"[x%2 or x%96 in{54,36,82,8}::2])

beata


In [97]:
x=int(input())+1
print("ablefa t a"[x%2 or x%86 in{8,50,72}::2])

beata


In [88]:
for i in np.concatenate([A, B]):
    x = i + 1
    a = x%2 or x%96 in{54,36,82,8}
    b = x%2 or x%86 in{8,40,72}
    if a != b:
        print(i, a, b)
        break

999971 True False


In [133]:
print("ablefa t a"[(x:=1+int(input())%86)in{8,50,72}or x%2::2])

alf  


In [153]:
D = (C - np.roll(C, 1))[1:]
D, np.gcd.reduce(D), np.gcd.reduce(D[:-1])


(array([   430, 887068, 112466]), 2, 2)

In [156]:
np.gcd(887505-7,430)

2

In [159]:
np.gcd(999971-437,887505-437)

2

In [175]:
print("ablefa t a"[((x:=1+int(input())%43)in{7,8,29})or x%2::2])
print(A, B)

beata
[   129    987    411    537    435    999 948731 123689 549387 478911
 548937 483135 439827 999999 999997 999995      5] [    948     104     198     562     437    1000  109754  129876  587462
  999998  999971  887505  465512 1000000       6       7]


In [192]:
for i in np.concatenate([A, B]):
    x = i + 1
    a = "ablefa t a"[x%2 or x%96 in{54,36,82,8}::2]
    b = "ablefa t a"(x:=1+int(input()))%43in{7,8,29}or x%2::2]
    if a != b:
        print(i, a, b)
        break

SyntaxError: invalid syntax (737784439.py, line 4)

In [187]:
i = 129
x = i + 1
x%2 or x%96 in{54,36,82,8}, (x:=1+i)%43in{7,8,29}or x%2

(False, 0)

In [181]:
130%96

34

In [182]:
(x:=1+i%43)in{7,8,29}

False

In [190]:
print("ablefa t a"[((x:=1+int(input()))%43in{7,8,29})or x%2::2])

alf  


In [393]:
for i in np.concatenate([A, B]):
    x = i + 1
    a = "ablefa t a"[x%2 or x%96in{54,36,82,8}::2]
    b = "baelaft a"[(x:=i%86%42%22)%2-(x==7)::2]
    if a.strip() != b.strip():
        print(i, a, b)
        break

In [233]:
i = 129
i%43in{6,7,28}

False

In [262]:
print("ablefa t a"[(x:=int(input()))%86%42%22==7or~x%2::2])

alf  


In [743]:
import numpy as np

A = np.array(A)
B = np.array(B)
C = np.array([7, 437, 887505, 999971])

M = 86
O = 42
P = 22
Q = 22
A % M % O % P % Q, B % M % O % P % Q, C % M % O % P % Q, np.intersect1d(A % M % O % P % Q, C % M % O % P % Q)

(array([ 1, 19,  3, 21,  5, 11,  1, 21, 19, 21,  1,  9,  1, 13, 11,  9,  5],
       dtype=int32),
 array([ 2, 18,  4,  4,  7, 12, 18, 16, 18, 12,  7,  7, 16, 14,  6,  7],
       dtype=int32),
 array([7, 7, 7, 7], dtype=int32),
 array([], dtype=int32))

In [3]:
A=np.sort(A)
B = np.sort(B)
C = np.sort(C)
A,B,C

(array([     5,    129,    411,    435,    537,    987,    999, 123689,
        439827, 478911, 483135, 548937, 549387, 948731, 999995, 999997,
        999999]),
 array([      6,       7,     104,     198,     437,     562,     948,
           1000,  109754,  129876,  465512,  587462,  887505,  999971,
         999998, 1000000]),
 array([     7,    437, 887505, 999971]))

In [299]:
np.log(A),np.log(C)

(array([ 1.60943791,  4.8598124 ,  6.01859321,  6.07534603,  6.28599809,
         6.89467004,  6.90675478, 11.72552563, 12.99413675, 13.07927006,
        13.0880514 , 13.21573896, 13.21655839, 13.76288058, 13.81550556,
        13.81550756, 13.81550956]),
 array([ 1.94591015,  6.0799332 , 13.69616943, 13.81548156]))

In [342]:
"1234567890"[-5::2]

'680'

In [ ]:
D = (C - np.roll(C, 1))[1:]
D, np.gcd.reduce(D), np.gcd.reduce(D[:-1])


(array([   430, 887068, 112466]), 2, 2)

In [758]:
# M = 69
# O = 29
# P = 4
# M = 86
# O = 32
# P = 10
# M = 91
# O = 46
# P = 500
# M,O,P=86,42,22
M,O,P=740,238,8
Q = 1

X = (A * Q) % M % O % P
Y = (B * Q) % M % O % P
Z = (C * Q) % M % O % P
# X &= 3
# Y &= 3
# Z &= 3
# X &= 7
# Y &= 7
# Z &= 7
# X &= 6
# Y &= 6
# Z &= 6
# X -= 6
# Y -= 6
# Z -= 6
# X = X % 2 * (X - 1)
# Y = Y % 2 * (Y - 1)
# Z = Z % 2 * (Z - 1)
# X = ~X
# Y = ~Y
# Z = ~Z
# X = (0<X) - (~A % 2)
# Y = (0<Y) - (~B % 2)
# Z = (0<Z) - (~C % 2)
# X = X // 3
# Y = Y // 3
# Z = Z // 3
# X = A%2-X//3
# Y = B%2-Y//3
# Z = C%2-Z//3
# print(B%2,Y//3)
# X = X//3 | ~A%2
# Y = Y//3 | ~B%2
# Z = Z//3 | ~C%2
# X = X%2-(X>6)
# Y = Y%2-(Y>6)
# X *= X*3
# Y *= Y*3
# X = (X&6)+(X&1)
# Y = (Y&6)+(Y&1)
X, Y, Z, np.intersect1d(X,Z)

(array([5, 1, 5, 5, 5, 1, 5, 5, 5, 3, 3, 1, 5, 3, 1, 3, 5], dtype=int32),
 array([6, 7, 0, 6, 7, 6, 0, 6, 2, 2, 4, 6, 7, 7, 4, 6], dtype=int32),
 array([7, 7, 7, 7], dtype=int32),
 array([], dtype=int32))

In [729]:
print("baelaft a"[(x:=int(input())%86%42%22)%2-(x==7)::2])

ValueError: invalid literal for int() with base 10: ''

In [ ]:
print("ablefa t a"[(x:=int(input()))%86%42%22==7or~x%2::2])

In [484]:
print("baelaft a"[(x:=int(input())%86%42%22-6)%2or~x-1::2])

alf 


In [485]:
print("baelaft a"[(x:=int(input())%86%42%22)%2==7::2])

ValueError: invalid literal for int() with base 10: ''

In [528]:
print("ablefa t a"[((x:=int(input()))%96%46%7==0)+~x%2::2])

beata


In [548]:
((x:=int(input()))%96%53%7>0)-(~x%2)

0

In [565]:
print("baelaft a"[(0<(x:=int(input()))%96%53%7)-~x%2::2])

beata


In [566]:
print("baelaft a"[-~(x:=int(input()))%2+(0<x%96%53%7)::2])

SyntaxError: cannot use assignment expressions with operator (676437240.py, line 1)

In [626]:
print("ablefa t a"[((x:=int(input()))%69%29%4>2)|~x%2::2])

alf 


In [633]:
print("ablefa t a"[2<(x:=int(input()))%69%29%4or~x%2::2])

beata


In [634]:
print("ablefa t a"[2<(x:=int(input()))%69%29%4|~x%2::2])

alf  


In [635]:
for i in np.concatenate([A, B]):
    x = i + 1
    a = "ablefa t a"[x%2 or x%96in{54,36,82,8}::2]
    b = "ablefa t a"[2<(x:=i)%69%29%4or~x%2::2]
    if a.strip() != b.strip():
        print(i, a, b)
        break

C:\Users\0\AppData\Local\Temp\ipykernel_23688\3564680977.py:4: DeprecationWarning: In future, it will be an error for 'np.bool_' scalars to be interpreted as an index
  b = "ablefa t a"[2<(x:=i)%69%29%4or~x%2::2]


In [715]:
for i in np.concatenate([A, B]):
    x = i + 1
    a = "ablefa t a"[x%2 or x%96in{54,36,82,8}::2]
    b = "ablefa t a"[~(x:=i)%2|x%69%29%4//3::2]
    if a.strip() != b.strip():
        print(i, a, b)
        break

In [646]:
print("ablefa t a"[~(x:=int(input()))%2|x%69%29%4//3::2])

alf  


In [724]:
for i in np.concatenate([A, B]):
    x = i + 1
    a = "ablefa t a"[x%2 or x%96in{54,36,82,8}::2]
    b = "baelaft a"[(x:=i)%2&(x%69%29%4<3)::2]
    if a.strip() != b.strip():
        print(i, a, b)
        break

In [651]:
print("baelaft a"[(x:=int(input()))%2&(x%69%29%4<3)::2])

beata


In [661]:
for i in np.concatenate([A, B]):
    x = i + 1
    a = "ablefa t a"[x%2 or x%96in{54,36,82,8}::2]
    b = "ablefa t a"[~(x:=i)%2|x%69%29%4//3::2]
    if a.strip() != b.strip():
        print(i, a, b)
        break

In [ ]:
print("ablefa t a"[~(x:=int(input()))%2|x%69%29%4//3::2])

In [665]:
for i in np.concatenate([A, B]):
    x = i + 1
    a = "ablefa t a"[x%2 or x%96in{54,36,82,8}::2]
    b = "baelaft a"[(x:=i)%2&x%69%29%4::2]
    if a.strip() != b.strip():
        print(i, a, b)
        break

129 alf   beata


In [706]:
for i in np.concatenate([A, B]):
    x = i + 1
    a = "ablefa t a"[x%2 or x%96in{54,36,82,8}::2]
    b = "baelaft a"[((x:=i%86%32%10)&6==6)or(x&1==1)::2]
    if a.strip() != b.strip():
        print(i, a, b)
        break

6 beata alf 


C:\Users\0\AppData\Local\Temp\ipykernel_23688\529905282.py:4: DeprecationWarning: In future, it will be an error for 'np.bool_' scalars to be interpreted as an index
  b = "baelaft a"[((x:=i%86%32%10)&6==6)or(x&1==1)::2]


In [680]:
print("baelaft a"[(x:=int(input())%86%42%22&7)%2-x>6::2])

beata


In [759]:
for i in np.concatenate([A, B]):
    x = i + 1
    a = "ablefa t a"[x%2 or x%96in{54,36,82,8}::2]
    b = "baelaft a"[i%740%238%8in(1,3,5)::2]
    if a.strip() != b.strip():
        print(i, a, b)
        break

In [ ]:
print('baelaft a'[int(input())%740%238%8in(1,3,5)::2])

In [32]:
import numpy as np
D = {948:1,104:1,129:0,987:0,411:0,198:1,562:1,537:0,435:0,437:1,999:0,1000:1,948731:0,109754:1,123689:0,549387:0,478911:0,129876:1,587462:1,548937:0,483135:0,439827:0,999999:0,999998:1,999997:0,999995:0,999971:1,887505:1,465512:1,1000000:1,5:0,6:1,7:1}
A = []
B = []
for key, value in D.items():
    if value == 1: B.append(key)
    else: A.append(key)

A, B = np.sort(np.array(A)), np.sort(np.array(B))
A, B, np.where(B % 2 == 1)

(array([     5,    129,    411,    435,    537,    987,    999, 123689,
        439827, 478911, 483135, 548937, 549387, 948731, 999995, 999997,
        999999]),
 array([      6,       7,     104,     198,     437,     562,     948,
           1000,  109754,  129876,  465512,  587462,  887505,  999971,
         999998, 1000000]),
 (array([ 1,  4, 12, 13], dtype=int64),))

In [145]:
for m1 in range(2, 1000, 2):
    for m2 in range(2, m1 + 2, 2):
        for m3 in range(2, m2 + 2, 2):
            a = A % m1 % m2 % m3
            b = B % m1 % m2 % m3
            c = np.intersect1d(a, b)
            if len(c) == 0 and (len(set(a)) < 4 or len(set(b)) < 4): print(m1, m2, m3, len(set(a)), len(set(b)))

472 76 10 3 7


KeyboardInterrupt: 

In [56]:
m1, m2, m3 = 472, 76, 10
set(A % m1 % m2 % m3), set(B % m1 % m2 % m3)

({1, 3, 5}, {0, 2, 4, 6, 7, 8, 9})

In [78]:
for m1 in range(2, 1000, 2):
    for m2 in range(1, 1000, 2):
        a = (A % m1) & m2
        b = (B % m1) & m2
        c = np.intersect1d(a, b)
        if len(c) == 0 and len(set(a)) < 4: print(m1, m2, len(set(a)))

346 35 3
346 547 3


In [74]:
m1, m2, = 346, 35
set(A % m1 & m2), set(B % m1 & m2)

({1, 33, 35}, {0, 2, 3, 32, 34})

In [75]:
for i in np.concatenate([A, B]):
    x = i + 1
    a = "ablefa t a"[x%2 or x%96in{54,36,82,8}::2]
    b = "baelaft a"[i%346&35in(1,33,35)::2]
    if a.strip() != b.strip():
        print(i, a, b)
        break

In [ ]:
print('baelaft a'[int(input())%346&35in(1,33,35)::2])

In [79]:
for m1 in range(1, 1000):
    for m2 in range(1, 1000):
        a = (A & m1) % m2
        b = (B & m1) % m2
        c = np.intersect1d(a, b)
        if len(c) == 0 and len(set(a)) < 4: print(m1, m2, len(set(a)))

In [80]:
for m1 in range(1, 1000):
    for m2 in range(1, 1000):
        a = (A % m1) & m2
        b = (B % m1) & m2
        c = np.intersect1d(a, b)
        if len(c) == 0 and len(set(a)) < 4: print(m1, m2, len(set(a)))

346 35 3
346 547 3


In [144]:
for m1 in range(1, 1000):
    for m2 in range(1, 1000):
        a = (A % m1) ^ m2
        b = (B % m1) ^ m2
        c = np.intersect1d(a, b)
        if len(c) == 0 and (len(set(a)) < 4 or len(set(b)) < 4): print(m1, m2, m3, len(set(a)), len(set(b)))

In [82]:
for m1 in range(1, 1000):
    for m2 in range(1, 1000):
        a = (A ^ m1) % m2
        b = (B ^ m1) % m2
        c = np.intersect1d(a, b)
        if len(c) == 0 and len(set(a)) < 4: print(m1, m2, len(set(a)))

In [143]:
for m1 in range(1, 100):
    for m2 in range(1, 100):
        for m3 in range(1, 20):
            a = ((A % m1) % m2) & m3
            b = ((B % m1) % m2) & m3
            c = np.intersect1d(a, b)
            if len(c) == 0 and (len(set(a)) < 4 or len(set(b)) < 4): print(m1, m2, m3, len(set(a)), len(set(b)))

92 50 11 3 5


In [100]:
m1, m2, m3 = 92, 50, 11
set(((A % m1) % m2) & m3), set(((B % m1) % m2) & m3)

({1, 9, 11}, {0, 2, 3, 8, 10})

In [102]:
for i in np.concatenate([A, B]):
    x = i + 1
    a = "ablefa t a"[x%2 or x%96in{54,36,82,8}::2]
    b = "baelaft a"[i%92%50&11in(1,9,11)::2]
    if a.strip() != b.strip():
        print(i, a, b)
        break

In [103]:
print('baelaft a'[int(input())%92%50&11in(1,9,11)::2])

alf 


In [142]:
for m1 in range(1, 1000):
    for m2 in range(1, 1000):
        a = (A % m1) | m2
        b = (B % m1) | m2
        c = np.intersect1d(a, b)
        if len(c) == 0 and (len(set(a)) < 4 or len(set(b)) < 4): print(m1, m2, m3, len(set(a)), len(set(b)))

346 476 99 3 5
346 988 99 3 5


In [109]:
m1, m2, = 346, 476
set(A % m1 | m2), set(B % m1 | m2)

({477, 509, 511}, {476, 478, 479, 508, 510})

In [112]:
for m1 in range(1, 1000):
    for m2 in range(1, 100):
        a = (A ^ m1) & m2
        b = (B ^ m1) & m2
        c = np.intersect1d(a, b)
        if len(c) == 0 and (len(set(a)) < 4 or len(set(b)) < 4): print(m1, m2, m3, len(set(a)), len(set(b)))

1 91 9
2 91 9
3 91 9
4 91 9
5 91 9
6 91 9
7 91 9
8 91 9
9 91 9
10 91 9
11 91 9
12 91 9
13 91 9
14 91 9
15 91 9
16 91 9
17 91 9
18 91 9
19 91 9
20 91 9
21 91 9
22 91 9
23 91 9
24 91 9
25 91 9
26 91 9
27 91 9
28 91 9
29 91 9
30 91 9
31 91 9
32 91 9
33 91 9
34 91 9
35 91 9
36 91 9
37 91 9
38 91 9
39 91 9
40 91 9
41 91 9
42 91 9
43 91 9
44 91 9
45 91 9
46 91 9
47 91 9
48 91 9
49 91 9
50 91 9
51 91 9
52 91 9
53 91 9
54 91 9
55 91 9
56 91 9
57 91 9
58 91 9
59 91 9
60 91 9
61 91 9
62 91 9
63 91 9
64 91 9
65 91 9
66 91 9
67 91 9
68 91 9
69 91 9
70 91 9
71 91 9
72 91 9
73 91 9
74 91 9
75 91 9
76 91 9
77 91 9
78 91 9
79 91 9
80 91 9
81 91 9
82 91 9
83 91 9
84 91 9
85 91 9
86 91 9
87 91 9
88 91 9
89 91 9
90 91 9
91 91 9
92 91 9
93 91 9
94 91 9
95 91 9
96 91 9
97 91 9
98 91 9
99 91 9
100 91 9
101 91 9
102 91 9
103 91 9
104 91 9
105 91 9
106 91 9
107 91 9
108 91 9
109 91 9
110 91 9
111 91 9
112 91 9
113 91 9
114 91 9
115 91 9
116 91 9
117 91 9
118 91 9
119 91 9
120 91 9
121 91 9
122 91 9
123 91 9
1

In [115]:
m1, m2, = 1, 91
set((A ^ m1) & m2), set((B ^ m1) & m2)

({0, 8, 10, 18, 24, 26, 66, 72, 90},
 {2, 3, 16, 17, 19, 27, 65, 67, 73, 80, 81})

In [154]:
for m1 in range(1, 100):
    for m2 in range(1, 100):
        for m3 in range(1, 100):
            a = ((A % m1) & m2) % m3
            b = ((B % m1) & m2) % m3
            c = np.intersect1d(a, b)
            if len(c) == 0 and (len(set(a)) < 4 or len(set(b)) < 4): print(m1, m2, m3, len(set(a)), len(set(b)))

86 23 9 3 6
86 23 18 3 7


In [140]:
m1, m2, m3 = 86, 23, 9
set(((A % m1) & m2) % m3), set(((B % m1) & m2) % m3)

({1, 3, 5}, {0, 2, 4, 6, 7, 8})

In [123]:
for m1 in range(1, 1000):
    for m2 in range(1, 1000):
        a = (A ^ m1) % m2
        b = (B ^ m1) % m2
        c = np.intersect1d(a, b)
        if len(c) == 0 and len(set(a)) < 5: print(m1, m2, len(set(a)))

In [138]:
m1, m2, = 346, 35
set((A % m1) & m2), set((B % m1) & m2)

({1, 33, 35}, {0, 2, 3, 32, 34})

In [127]:
set(A & 35), set(B & 35)

({1, 3, 33, 35}, {0, 1, 2, 3, 32, 33, 34, 35})

In [157]:
for i in np.concatenate([A, B]):
    x = i + 1
    a = "ablefa t a"[x%2 or x%96in{54,36,82,8}::2]
    b = "baelaft a"[(i%86&23)%9in(1,3,5)::2]
    if a.strip() != b.strip():
        print(i, a, b)
        break

129 alf   beata


In [156]:
print('baelaft a'[(int(input())%86&23)%9in(1,3,5)::2])

alf 


In [150]:
for m1 in range(1, 100):
    for m2 in range(1, 1000):
        a = (A // m1) % m2
        b = (B // m1) % m2
        c = np.intersect1d(a, b)
        if len(c) == 0 and len(set(a)) < 4: print(m1, m2, len(set(a)))

In [158]:
m1, m2, = 86, 23
set((A % m1) & m2), set((B % m1) & m2)

({1, 3, 5, 19, 21, 23}, {2, 4, 6, 7, 16, 17, 18, 22})

In [159]:
for i in np.concatenate([A, B]):
    x = i + 1
    a = "ablefa t a"[x%2 or x%96in{54,36,82,8}::2]
    b = "baelaft a"[(i%346&35)%17in(1,33)::2]
    if a.strip() != b.strip():
        print(i, a, b)
        break

In [160]:
for m1 in range(2, 1000, 2):
    for m2 in range(1, 100):
        for m3 in range(1, 100):
            a = ((A % m1) & m2) % m3
            b = ((B % m1) & m2) % m3
            c = np.intersect1d(a, b)
            if len(c) == 0 and len(set(a)) < 4: print(m1, m2, m3, len(set(a)), len(set(b)))

86 23 9 3 6
86 23 18 3 7
346 35 9 3 5
346 35 12 3 5
346 35 13 3 5
346 35 14 3 5
346 35 17 2 4
346 35 18 3 5
346 35 19 3 5
346 35 20 3 5
346 35 21 3 5
346 35 22 3 5
346 35 23 3 5
346 35 24 3 5
346 35 25 3 5
346 35 26 3 5
346 35 27 3 5
346 35 28 3 5
346 35 29 3 4
346 35 34 2 4
346 35 36 3 5
346 35 37 3 5
346 35 38 3 5
346 35 39 3 5
346 35 40 3 5
346 35 41 3 5
346 35 42 3 5
346 35 43 3 5
346 35 44 3 5
346 35 45 3 5
346 35 46 3 5
346 35 47 3 5
346 35 48 3 5
346 35 49 3 5
346 35 50 3 5
346 35 51 3 5
346 35 52 3 5
346 35 53 3 5
346 35 54 3 5
346 35 55 3 5
346 35 56 3 5
346 35 57 3 5
346 35 58 3 5
346 35 59 3 5
346 35 60 3 5
346 35 61 3 5
346 35 62 3 5
346 35 63 3 5
346 35 64 3 5
346 35 65 3 5
346 35 66 3 5
346 35 67 3 5
346 35 68 3 5
346 35 69 3 5
346 35 70 3 5
346 35 71 3 5
346 35 72 3 5
346 35 73 3 5
346 35 74 3 5
346 35 75 3 5
346 35 76 3 5
346 35 77 3 5
346 35 78 3 5
346 35 79 3 5
346 35 80 3 5
346 35 81 3 5
346 35 82 3 5
346 35 83 3 5
346 35 84 3 5
346 35 85 3 5
346 35 86 3 5
346 35 87 

In [4]:
A,B,C

(array([     5,    129,    411,    435,    537,    987,    999, 123689,
        439827, 478911, 483135, 548937, 549387, 948731, 999995, 999997,
        999999]),
 array([      6,       7,     104,     198,     437,     562,     948,
           1000,  109754,  129876,  465512,  587462,  887505,  999971,
         999998, 1000000]),
 array([     7,    437, 887505, 999971]))

In [15]:
for i in range(10, 100, 2):
    if len(np.intersect1d(A % i, C % i)) == 0:
        print(i)

58
64
68
74
80
86
88
92
96


In [27]:
M = 58
A % M, B % M, C % M, np.intersect1d(A % M, C % M)

(array([ 5, 13,  5, 29, 15,  1, 13, 33, 13,  5, 53, 25, 11, 25, 17, 19, 21],
       dtype=int32),
 array([ 6,  7, 46, 24, 31, 40, 20, 14, 18, 14,  4, 38, 47, 51, 20, 22],
       dtype=int32),
 array([ 7, 31, 47, 51], dtype=int32),
 array([], dtype=int32))

In [30]:
for i in range(10, 1000):
    if len(np.intersect1d(A & i, C & i)) == 0:
        print(i)

62
63
90
91
94
95
122
123
126
127
154
155
158
159
182
183
186
187
190
191
218
219
222
223
238
239
246
247
250
251
254
255
282
283
286
287
314
315
318
319
346
347
350
351
366
367
374
375
378
379
382
383
410
411
414
415
438
439
442
443
446
447
474
475
478
479
494
495
502
503
506
507
510
511
542
543
558
559
574
575
602
603
606
607
618
619
622
623
626
627
630
631
634
635
638
639
666
667
670
671
682
683
686
687
690
691
694
695
698
699
702
703
730
731
734
735
746
747
750
751
754
755
758
759
762
763
766
767
794
795
798
799
810
811
814
815
826
827
830
831
858
859
862
863
874
875
878
879
882
883
886
887
890
891
894
895
922
923
926
927
938
939
942
943
946
947
950
951
954
955
958
959
986
987
990
991


In [31]:
M = 62
A & M, B & M, C & M, np.intersect1d(A & M, C & M)

(array([ 4,  0, 26, 50, 24, 26, 38, 40, 18, 62, 62,  8, 10, 58, 58, 60, 62],
       dtype=int32),
 array([ 6,  6, 40,  6, 52, 50, 52, 40, 58, 20, 40,  6, 16, 34, 62,  0],
       dtype=int32),
 array([ 6, 52, 16, 34], dtype=int32),
 array([], dtype=int32))

In [1]:
import os
root = "appelspelet.data/"
A = []
B = []
S = ""
for file in os.listdir(os.fsencode(root)):
      inname = os.fsdecode(file)
      if inname.endswith(".in"):
         outname = inname[:-2] + "ans"
         with open(root + inname) as I:
            with open(root + outname) as O:
               i = I.read()[:-1]
               o = O.read()[:-1]
               S += i + ":"
               S +=(str) (0 if o == "alf" else 1) + ","
               if o == "alf":
                  A.append(int(i))
               else:
                  B.append(int(i))

S = S[:-1]
print(S)

948:1,104:1,129:0,987:0,411:0,198:1,562:1,537:0,435:0,437:1,999:0,1000:1,948731:0,109754:1,123689:0,549387:0,478911:0,129876:1,587462:1,548937:0,483135:0,439827:0,999999:0,999998:1,999997:0,999995:0,999971:1,887505:1,465512:1,1000000:1,5:0,6:1,7:1


In [2]:
import numpy as np

A = np.array(A)
B = np.array(B)
C = np.array([7, 437, 887505, 999971])

M = 43
A % M, B % M, C % M, np.intersect1d(A % M, C % M)

(array([ 0, 41, 24, 21,  5, 10, 22, 21, 19, 20, 42, 30, 23, 34, 32, 30,  5],
       dtype=int32),
 array([ 2, 18, 26,  3,  7, 11, 18, 16, 39, 33,  6, 28, 37, 35,  6,  7],
       dtype=int32),
 array([ 7,  7, 28,  6], dtype=int32),
 array([], dtype=int32))

In [3]:
A=np.sort(A)
B = np.sort(B)
C = np.sort(C)
A,B,C

(array([     5,    129,    411,    435,    537,    987,    999, 123689,
        439827, 478911, 483135, 548937, 549387, 948731, 999995, 999997,
        999999]),
 array([      6,       7,     104,     198,     437,     562,     948,
           1000,  109754,  129876,  465512,  587462,  887505,  999971,
         999998, 1000000]),
 array([     7,    437, 887505, 999971]))

In [27]:
for M in range(2, 100):
    if len(np.intersect1d(A % M, B % M)) == 0:
        print(M, A % M, B % M, np.intersect1d(A % M, B % M))

37 [ 5 18  4 28 19 25  0 35  8 20 26  5 11 14 33 35  0] [ 6  7 30 13 30  7 23  1 12  6 15 13 23  9 36  1] []
43 [ 5  0 24  5 21 41 10 21 23 20 30 42 19 22 30 32 34] [ 6  7 18 26  7  3  2 11 18 16 37 39 28  6 33 35] []
58 [ 5 13  5 29 15  1 13 33 13  5 53 25 11 25 17 19 21] [ 6  7 46 24 31 40 20 14 18 14  4 38 47 51 20 22] []
64 [ 5  1 27 51 25 27 39 41 19 63 63  9 11 59 59 61 63] [ 6  7 40  6 53 50 52 40 58 20 40  6 17 35 62  0] []
68 [ 5 61  3 27 61 35 47 65  3 55 63 41 15 63 55 57 59] [ 6  7 36 62 29 18 64 48  2 64 52 10 37 31 58 60] []
74 [ 5 55 41 65 19 25 37 35 45 57 63  5 11 51 33 35 37] [ 6  7 30 50 67 44 60 38 12  6 52 50 23  9 36 38] []
75 [ 5 54 36 60 12 12 24 14 27 36 60 12 12 56 20 22 24] [ 6  7 29 48 62 37 48 25 29 51 62 62 30 71 23 25] []
80 [ 5 49 11 35 57 27 39  9 67 31 15 57 27 11 75 77 79] [ 6  7 24 38 37  2 68 40 74 36 72 22 65 51 78  0] []
83 [ 5 46 79 20 39 74  3 19 10  1 75 58 10 41 11 13 15] [ 6  7 21 32 22 64 35  4 28 64 48 71 69 70 14 16] []
86 [ 5 43 67  5 21 

In [11]:
M = 37
print(M, A % M, B % M, np.intersect1d(A % M, B % M))

37 [ 5 18  4 28 19 25  0 35  8 20 26  5 11 14 33 35  0] [ 6  7 30 13 30  7 23  1 12  6 15 13 23  9 36  1] []


In [35]:
M = 37
S = ["_"] * M
for i in range(M):
    if i in A % M:
        S[i] = "0"
    elif i in B % M:
        S[i] = "1"
"".join(S)

'01__001101_01101__000__1_00_0_1__0_01'

In [34]:
M = 58
S = ["_"] * M
for i in range(M):
    if i in A % M:
        S[i] = "0"
    elif i in B % M:
        S[i] = "1"
"".join(S)

'_0__1011___0_010_010101_10___0_1_0____1_1_____11___1_0____'

In [33]:
M = 74
S = ["_"] * M
for i in range(M):
    if i in A % M:
        S[i] = "0"
    elif i in B % M:
        S[i] = "1"
"".join(S)

'_____011_1_01______0___1_0____1__0_0101__0__10____101__0_0__1__0_0_1______'

In [32]:
M = 75
S = ["_"] * M
for i in range(M):
    if i in A % M:
        S[i] = "0"
    elif i in B % M:
        S[i] = "1"
"".join(S)

'_____011____0_0_____0_0101_0_11_____01__________1__1__0_0___0_1________1___'