In [741]:
import os
root = "appelspelet.data/"
A = []
B = []
S = ""
for file in os.listdir(os.fsencode(root)):
      inname = os.fsdecode(file)
      if inname.endswith(".in"):
         outname = inname[:-2] + "ans"
         with open(root + inname) as I:
            with open(root + outname) as O:
               i = I.read()[:-1]
               o = O.read()[:-1]
               S += i + ":"
               S +=(str) (0 if o == "alf" else 1) + ","
               if o == "alf":
                  A.append(int(i))
               else:
                  B.append(int(i))

S = S[:-1]
print(S)

948:1,104:1,129:0,987:0,411:0,198:1,562:1,537:0,435:0,437:1,999:0,1000:1,948731:0,109754:1,123689:0,549387:0,478911:0,129876:1,587462:1,548937:0,483135:0,439827:0,999999:0,999998:1,999997:0,999995:0,999971:1,887505:1,465512:1,1000000:1,5:0,6:1,7:1


In [20]:
D={948:1,104:1,129:0,987:0,411:0,198:1,562:1,537:0,435:0,437:1,999:0,1000:1,948731:0,109754:1,123689:0,549387:0,478911:0,129876:1,587462:1,548937:0,483135:0,439827:0,999999:0,999998:1,999997:0,999995:0,999971:1,887505:1,465512:1,1000000:1,5:0,6:1,7:1}
N = int(input())
print("alf" if D[N] == 0 else "beata")

beata


In [21]:
D

{948: 1,
 104: 1,
 129: 0,
 987: 0,
 411: 0,
 198: 1,
 562: 1,
 537: 0,
 435: 0,
 437: 1,
 999: 0,
 1000: 1,
 948731: 0,
 109754: 1,
 123689: 0,
 549387: 0,
 478911: 0,
 129876: 1,
 587462: 1,
 548937: 0,
 483135: 0,
 439827: 0,
 999999: 0,
 999998: 1,
 999997: 0,
 999995: 0,
 999971: 1,
 887505: 1,
 465512: 1,
 1000000: 1,
 5: 0,
 6: 1,
 7: 1}

In [22]:
S = ""
for file in os.listdir(os.fsencode(root)):
      inname = os.fsdecode(file)
      if inname.endswith(".in"):
         outname = inname[:-2] + "ans"
         with open(root + inname) as I:
            with open(root + outname) as O:
                if O.read()[:-1] == "beata":
                    S += I.read()[:-1] + ","

S = S[:-1]
print(S)

948,104,198,562,437,1000,109754,129876,587462,999998,999971,887505,465512,1000000,6,7


In [31]:
print("beata"if int(input())in{948,104,198,562,437,1000,109754,129876,587462,999998,999971,887505,465512,1000000,6,7}else"alf")

beata


In [26]:
S

{6,
 7,
 104,
 198,
 437,
 562,
 948,
 1000,
 109754,
 129876,
 465512,
 587462,
 887505,
 999971,
 999998,
 1000000}

In [15]:
x=int(input())+1
print("ablefa t a"[x%2 or x in{438,999972,887506,8}::2])

beata


In [167]:
import numpy as np

A = np.array(A)
B = np.array(B)
C = np.array([7, 437, 887505, 999971])

M = 43
A % M, B % M, C % M, np.intersect1d(A % M, C % M)

(array([ 0, 41, 24, 21,  5, 10, 22, 21, 19, 20, 42, 30, 23, 34, 32, 30,  5],
       dtype=int32),
 array([ 2, 18, 26,  3,  7, 11, 18, 16, 39, 33,  6, 28, 37, 35,  6,  7],
       dtype=int32),
 array([ 7,  7, 28,  6], dtype=int32),
 array([], dtype=int32))

In [89]:
x=int(input())+1
print("ablefa t a"[x%2 or x%96 in{54,36,82,8}::2])

beata


In [97]:
x=int(input())+1
print("ablefa t a"[x%2 or x%86 in{8,50,72}::2])

beata


In [88]:
for i in np.concatenate([A, B]):
    x = i + 1
    a = x%2 or x%96 in{54,36,82,8}
    b = x%2 or x%86 in{8,40,72}
    if a != b:
        print(i, a, b)
        break

999971 True False


In [133]:
print("ablefa t a"[(x:=1+int(input())%86)in{8,50,72}or x%2::2])

alf  


In [153]:
D = (C - np.roll(C, 1))[1:]
D, np.gcd.reduce(D), np.gcd.reduce(D[:-1])


(array([   430, 887068, 112466]), 2, 2)

In [156]:
np.gcd(887505-7,430)

2

In [159]:
np.gcd(999971-437,887505-437)

2

In [175]:
print("ablefa t a"[((x:=1+int(input())%43)in{7,8,29})or x%2::2])
print(A, B)

beata
[   129    987    411    537    435    999 948731 123689 549387 478911
 548937 483135 439827 999999 999997 999995      5] [    948     104     198     562     437    1000  109754  129876  587462
  999998  999971  887505  465512 1000000       6       7]


In [192]:
for i in np.concatenate([A, B]):
    x = i + 1
    a = "ablefa t a"[x%2 or x%96 in{54,36,82,8}::2]
    b = "ablefa t a"(x:=1+int(input()))%43in{7,8,29}or x%2::2]
    if a != b:
        print(i, a, b)
        break

SyntaxError: invalid syntax (737784439.py, line 4)

In [187]:
i = 129
x = i + 1
x%2 or x%96 in{54,36,82,8}, (x:=1+i)%43in{7,8,29}or x%2

(False, 0)

In [181]:
130%96

34

In [182]:
(x:=1+i%43)in{7,8,29}

False

In [190]:
print("ablefa t a"[((x:=1+int(input()))%43in{7,8,29})or x%2::2])

alf  


In [393]:
for i in np.concatenate([A, B]):
    x = i + 1
    a = "ablefa t a"[x%2 or x%96in{54,36,82,8}::2]
    b = "baelaft a"[(x:=i%86%42%22)%2-(x==7)::2]
    if a.strip() != b.strip():
        print(i, a, b)
        break

In [233]:
i = 129
i%43in{6,7,28}

False

In [262]:
print("ablefa t a"[(x:=int(input()))%86%42%22==7or~x%2::2])

alf  


In [743]:
import numpy as np

A = np.array(A)
B = np.array(B)
C = np.array([7, 437, 887505, 999971])

M = 86
O = 42
P = 22
Q = 22
A % M % O % P % Q, B % M % O % P % Q, C % M % O % P % Q, np.intersect1d(A % M % O % P % Q, C % M % O % P % Q)

(array([ 1, 19,  3, 21,  5, 11,  1, 21, 19, 21,  1,  9,  1, 13, 11,  9,  5],
       dtype=int32),
 array([ 2, 18,  4,  4,  7, 12, 18, 16, 18, 12,  7,  7, 16, 14,  6,  7],
       dtype=int32),
 array([7, 7, 7, 7], dtype=int32),
 array([], dtype=int32))

In [744]:
A=np.sort(A)
B = np.sort(B)
C = np.sort(C)
A,B,C

(array([     5,    129,    411,    435,    537,    987,    999, 123689,
        439827, 478911, 483135, 548937, 549387, 948731, 999995, 999997,
        999999]),
 array([      6,       7,     104,     198,     437,     562,     948,
           1000,  109754,  129876,  465512,  587462,  887505,  999971,
         999998, 1000000]),
 array([     7,    437, 887505, 999971]))

In [299]:
np.log(A),np.log(C)

(array([ 1.60943791,  4.8598124 ,  6.01859321,  6.07534603,  6.28599809,
         6.89467004,  6.90675478, 11.72552563, 12.99413675, 13.07927006,
        13.0880514 , 13.21573896, 13.21655839, 13.76288058, 13.81550556,
        13.81550756, 13.81550956]),
 array([ 1.94591015,  6.0799332 , 13.69616943, 13.81548156]))

In [342]:
"1234567890"[-5::2]

'680'

In [ ]:
D = (C - np.roll(C, 1))[1:]
D, np.gcd.reduce(D), np.gcd.reduce(D[:-1])


(array([   430, 887068, 112466]), 2, 2)

In [758]:
# M = 69
# O = 29
# P = 4
# M = 86
# O = 32
# P = 10
# M = 91
# O = 46
# P = 500
# M,O,P=86,42,22
M,O,P=740,238,8
Q = 1

X = (A * Q) % M % O % P
Y = (B * Q) % M % O % P
Z = (C * Q) % M % O % P
# X &= 3
# Y &= 3
# Z &= 3
# X &= 7
# Y &= 7
# Z &= 7
# X &= 6
# Y &= 6
# Z &= 6
# X -= 6
# Y -= 6
# Z -= 6
# X = X % 2 * (X - 1)
# Y = Y % 2 * (Y - 1)
# Z = Z % 2 * (Z - 1)
# X = ~X
# Y = ~Y
# Z = ~Z
# X = (0<X) - (~A % 2)
# Y = (0<Y) - (~B % 2)
# Z = (0<Z) - (~C % 2)
# X = X // 3
# Y = Y // 3
# Z = Z // 3
# X = A%2-X//3
# Y = B%2-Y//3
# Z = C%2-Z//3
# print(B%2,Y//3)
# X = X//3 | ~A%2
# Y = Y//3 | ~B%2
# Z = Z//3 | ~C%2
# X = X%2-(X>6)
# Y = Y%2-(Y>6)
# X *= X*3
# Y *= Y*3
# X = (X&6)+(X&1)
# Y = (Y&6)+(Y&1)
X, Y, Z, np.intersect1d(X,Z)

(array([5, 1, 5, 5, 5, 1, 5, 5, 5, 3, 3, 1, 5, 3, 1, 3, 5], dtype=int32),
 array([6, 7, 0, 6, 7, 6, 0, 6, 2, 2, 4, 6, 7, 7, 4, 6], dtype=int32),
 array([7, 7, 7, 7], dtype=int32),
 array([], dtype=int32))

In [729]:
print("baelaft a"[(x:=int(input())%86%42%22)%2-(x==7)::2])

ValueError: invalid literal for int() with base 10: ''

In [ ]:
print("ablefa t a"[(x:=int(input()))%86%42%22==7or~x%2::2])

In [484]:
print("baelaft a"[(x:=int(input())%86%42%22-6)%2or~x-1::2])

alf 


In [485]:
print("baelaft a"[(x:=int(input())%86%42%22)%2==7::2])

ValueError: invalid literal for int() with base 10: ''

In [528]:
print("ablefa t a"[((x:=int(input()))%96%46%7==0)+~x%2::2])

beata


In [548]:
((x:=int(input()))%96%53%7>0)-(~x%2)

0

In [565]:
print("baelaft a"[(0<(x:=int(input()))%96%53%7)-~x%2::2])

beata


In [566]:
print("baelaft a"[-~(x:=int(input()))%2+(0<x%96%53%7)::2])

SyntaxError: cannot use assignment expressions with operator (676437240.py, line 1)

In [626]:
print("ablefa t a"[((x:=int(input()))%69%29%4>2)|~x%2::2])

alf 


In [633]:
print("ablefa t a"[2<(x:=int(input()))%69%29%4or~x%2::2])

beata


In [634]:
print("ablefa t a"[2<(x:=int(input()))%69%29%4|~x%2::2])

alf  


In [635]:
for i in np.concatenate([A, B]):
    x = i + 1
    a = "ablefa t a"[x%2 or x%96in{54,36,82,8}::2]
    b = "ablefa t a"[2<(x:=i)%69%29%4or~x%2::2]
    if a.strip() != b.strip():
        print(i, a, b)
        break

C:\Users\0\AppData\Local\Temp\ipykernel_23688\3564680977.py:4: DeprecationWarning: In future, it will be an error for 'np.bool_' scalars to be interpreted as an index
  b = "ablefa t a"[2<(x:=i)%69%29%4or~x%2::2]


In [715]:
for i in np.concatenate([A, B]):
    x = i + 1
    a = "ablefa t a"[x%2 or x%96in{54,36,82,8}::2]
    b = "ablefa t a"[~(x:=i)%2|x%69%29%4//3::2]
    if a.strip() != b.strip():
        print(i, a, b)
        break

In [646]:
print("ablefa t a"[~(x:=int(input()))%2|x%69%29%4//3::2])

alf  


In [724]:
for i in np.concatenate([A, B]):
    x = i + 1
    a = "ablefa t a"[x%2 or x%96in{54,36,82,8}::2]
    b = "baelaft a"[(x:=i)%2&(x%69%29%4<3)::2]
    if a.strip() != b.strip():
        print(i, a, b)
        break

In [651]:
print("baelaft a"[(x:=int(input()))%2&(x%69%29%4<3)::2])

beata


In [661]:
for i in np.concatenate([A, B]):
    x = i + 1
    a = "ablefa t a"[x%2 or x%96in{54,36,82,8}::2]
    b = "ablefa t a"[~(x:=i)%2|x%69%29%4//3::2]
    if a.strip() != b.strip():
        print(i, a, b)
        break

In [ ]:
print("ablefa t a"[~(x:=int(input()))%2|x%69%29%4//3::2])

In [665]:
for i in np.concatenate([A, B]):
    x = i + 1
    a = "ablefa t a"[x%2 or x%96in{54,36,82,8}::2]
    b = "baelaft a"[(x:=i)%2&x%69%29%4::2]
    if a.strip() != b.strip():
        print(i, a, b)
        break

129 alf   beata


In [706]:
for i in np.concatenate([A, B]):
    x = i + 1
    a = "ablefa t a"[x%2 or x%96in{54,36,82,8}::2]
    b = "baelaft a"[((x:=i%86%32%10)&6==6)or(x&1==1)::2]
    if a.strip() != b.strip():
        print(i, a, b)
        break

6 beata alf 


C:\Users\0\AppData\Local\Temp\ipykernel_23688\529905282.py:4: DeprecationWarning: In future, it will be an error for 'np.bool_' scalars to be interpreted as an index
  b = "baelaft a"[((x:=i%86%32%10)&6==6)or(x&1==1)::2]


In [680]:
print("baelaft a"[(x:=int(input())%86%42%22&7)%2-x>6::2])

beata


In [759]:
for i in np.concatenate([A, B]):
    x = i + 1
    a = "ablefa t a"[x%2 or x%96in{54,36,82,8}::2]
    b = "baelaft a"[i%740%238%8in(1,3,5)::2]
    if a.strip() != b.strip():
        print(i, a, b)
        break

In [ ]:
print('baelaft a'[int(input())%740%238%8in(1,3,5)::2])